name: release

on:
  push:
    branches:
      - main
  # release:
  #   types: [created]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: 23.10.0

      - name: Build binary
        run: |
          node --experimental-sea-config sea-config.json
          cp $(command -v node) greet
          npx postject greet NODE_SEA_BLOB sea-prep.blob \
              --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2
        # see: https://nodejs.org/api/single-executable-applications.html

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@ef244123eb79f2f7a7e75d99086184180e6d0018 # v1.4.4
        with:
          subject-path: "greet"

      - name: Uplaod artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          path: "greet"
          name: "sea"

      - name: Ensure binary runs
        run: |
          ./greet

  publish:
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: 23.10.0
          registry-url: https://npm.pkg.github.com/
      - uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        with:
          name: "sea"
      - run: ls
      - run: |
          gh release create --generate-notes test greet
        env:
          GH_TOKEN: ${{ github.token }}
